spring: 
    application: 
        name: fiap-tc5-ecommerce-orchestrator-ms

server: 
    port: 8080
    servlet: 
        context-path: /ecommerce-orchestrator-ms/api/v1

springdoc: 
    api-docs.path: /api-docs
    swagger-ui.path: /swagger-ui.html

api:
    security:
        jwt:
            secret: ${JWT_SECRET:jwtecommercesystem}

microservices:
    user-ms:
        url: http://localhost:8081/ecommerce-management/api/v1/users
    item-ms:
        url: http://localhost:8082/ecommerce-management/api/v1/items
    cart-ms:
        url: http://localhost:8083/ecommerce-management/api/v1/carts
    payment-ms:
        url: http://localhost:8084/ecommerce-management/api/v1/payments
    session-ms:
        url: http://localhost:8085/ecommerce-management/api/v1/sessions
